version: "3.9"

services:
  nginx:
    image: nginx:alpine
    container_name: lde.nginx

  postgres:
    image: postgres:alpine
    container_name: lde.postgres

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: lde.pgadmin4

  redis:
    image: redis:alpine
    container_name: lde.redis

  identityserver:
    container_name: lde.identityserver
    build:
      context: ../istore-identityserver/.
      dockerfile: ../istore-identityserver/IdentityServer/IdentityServer/Dockerfile.dev

  catalog.api:
    container_name: lde.catalog.api
    build:
      context: ../istore-catalog/.
      dockerfile: ../istore-catalog/Catalog/Catalog.Host/Dockerfile.dev

  basket.api:
    container_name: lde.basket.api
    build:
      context: ../istore-basket/.
      dockerfile: ../istore-basket/Basket/Basket.Host/Dockerfile.dev

networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
